### ISSUE TITLE
`html->sxml` with escaped quotes breaks text into multiple nodes

### ISSUE THREAD

**Issue by ThatGeoGuy** [ashinn/alschemist#1]
This is admittedly something I noticed in CHICKEN Scheme, not Chibi, but I was told that the CHICKEN bindings for [html-parser](https://wiki.call-cc.org/eggref/5/html-parser) are just a thin wrapper around the same code for Chibi. 

Anyways, there's some weirdness with escaping quotes in text when using `html->sxml`. Perhaps a short example would be sufficient to explain the problem I'm encountering:

```scheme
(html->sxml "<p>foo&apos;bar&quot;baz</p>") ;=> (*TOP* (p "foo" "'" "bar" "\"" "baz"))
```

As a counter-example, I'll use the [ssax egg](https://wiki.call-cc.org/eggref/5/ssax):

```scheme
(call-with-input-string "<p>foo&apos;bar&quot;baz</p>" (cut ssax:xml->sxml <> '())) ;=> (*TOP* (p "foo'bar\"baz"))
```

I guess fundamentally it's a question of whether there should be one text node or not. I would argue that in this particular case, it should be a single node. I have been using html-parser to try and scrape some web pages, and this is extremely unexpected! Especially so if one uses `txpath` / `sxpath` on the final result, as `//p/text()` queries will not necessarily behave as expected. You would have to `(apply string-append ((txpath "//p/text()") sxml))` to the result to get the full contents of the text.

Is there a rationale for this, or is that some kind of limitation of the parser? I know that tags may also contain sub-tags in HTML, but I'm not sure a new node should be made if a tag's contents are not HTML tags themselves.

See copy of this ticket on [the CHICKEN bug tracker](https://bugs.call-cc.org/ticket/1805#ticket).

**Comment by ashinn** [comment]
Congrats on the first alschemist issue!

I think in general you can't rely on there being a single string and need to account for this, but let me double check - if SSAX always guarantees a single string then I'll match it.

**Comment by ThatGeoGuy** [comment]
Thanks, hah. 

My workaround for not having a single string was to apply `string-append` over each of the elements, but I think this is problematic in some instances. In particular, I think this would be an error in the case of actually nested tags, although per the HTML spec there is some weirdness with regards to nested elements in `<p>`-like tags.

In particular I am pretty sure something like:

```html
<p>
  Some text <a href='...'>with a link.</a>
  
  Some more text.
</p>
```

is often interpreted no differently from

```html
<p>
  Some text
</p>
<a href='...'>
  with a link.
</a>
<p>
  Some more text.
</p>
```

Although I'm sure this is probably an implementation detail of browser engines more than anything. 

But even in the above case, I expect another node in SXML for the `<a>` tag in the paragraph. I don't necessarily expect an extra node if there's e.g. `&nbsp;`, `&quot;`, etc. So you may be right that you can't always expect a single string, but I'm not sure that escaped characters are the distinguishing factor for that 🤔

**Comment by ashinn** [comment]
It looks like SSAX consistently condenses to a single string, I'll update it.

**Comment by ashinn** [comment]
Fixed.  For the more general issue of nested elements (a, spans, etc.) you can use something like html-strip on the subtree.
